### ISSUE TITLE
Pause after words in german language file is to long

### ISSUE THREAD

**Issue by Gernod** [EdgeTX/edgetx-sdcard-sounds#112]
The pause after the words in German language are too long. 

Example: Battery Voltage is pronounced: "ten         volts"  should be "ten volts"

**Comment by pfeerick** [comment]
If you have a long pause between words, try reloading the SD card pack, as you probably have the original un-trimmed audio from the repo, rather than the trimmed and normalised version that is in the releases. 

i.e. this is the audio from the repo for "ten" and "volt"... would run for nearly 3 seconds, with quite a delay after each file. 

![Screenshot 2024-05-30 204428](https://github.com/EdgeTX/edgetx-sdcard-sounds/assets/5500713/cdf189a1-5394-405d-9748-48c6f543a42b)

Whereas the audio in the release zip files is clipped much shorter, as well as normalised so it is louder, and would take less than half the time to play, with a much shorter delay after each file. 
![Screenshot 2024-05-30 204645](https://github.com/EdgeTX/edgetx-sdcard-sounds/assets/5500713/af1d713e-e400-49d5-9b24-cf142429a482)

**Comment by Gernod** [comment]
Indeed, you are right. Reloaded the right soundpack and its working. Thank you.

**Comment by pfeerick** [comment]
Glad that fixed it. Enjoy! :)
