### ISSUE TITLE
Add more words/phrases

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx-sdcard-sounds#26]
- SAFE on
- SAFE off
- timer 1 reset
- timer 2 reset
- timer 3 reset
- expo 1
- expo 2
- expo 3

Check for
- Launch Mode
- Loiter
- Return to Launch

**Comment by microraptor** [comment]
I included your suggestions to my PR (see above). These ones are included:

- safety on
- safety off
- timer 1 reset
- timer 2 reset
- timer 3 reset
- expo 1
- expo 2
- expo 3
- loiter

However, I did not include "launch mode", because it already exists as lncmod.wav and also not "return to launch", because "return to home" already exists as rth.wav.
